FADQ/igo2

- src/app/app.module.ts
- src/app/modules/catalog/catalog-browser/catalog-browser.component.ts
- src/app/modules/catalog/catalog-library/catalog-library-item.component.ts
- src/app/modules/map/index.ts
- src/app/modules/map/map-toolbar/map-toolbar.component.ts
- src/app/modules/map/map.module.ts
- src/app/modules/map/shared/index.ts
- src/app/modules/map/shared/map.service.ts
- src/app/modules/map/shared/map.ts
- src/app/modules/navigation/index.ts
- src/app/modules/navigation/place-selector/place-selector.component.ts
- src/app/modules/navigation/poi-selector/poi-selector.component.ts
- src/app/modules/navigation/shared/place.service.ts
- src/app/modules/overlay/shared/overlay.ts
- src/app/modules/tool/catalog-browser-tool/catalog-browser-tool.component.ts
- src/app/modules/tool/navigation-tool/navigation-tool.component.html
- src/app/modules/tool/navigation-tool/navigation-tool.component.ts
- src/app/modules/tool/search-results-tool/search-results-tool.component.ts
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.ts
The IgoMap from igo2-lib uses the"old" overlay
A new IgoMap extends the the IgoMap from igo2-lib and creates an instance of the new overlay.
This is the IgoMap that's in use in all our tools.
```
[ ] Yes
[ ] No
```
> extend the base IgoMap and add a default overlay

- src/app/modules/entity/entity-table/entity-table.component.html
- src/app/modules/entity/entity-table/entity-table.component.scss
- src/app/modules/entity/entity-table/entity-table.component.ts
- src/app/modules/entity/entity-table/entity-table.module.ts
- src/app/modules/entity/entity-table/entity-table.variables.scss
- src/app/modules/entity/entity-table/index.ts
- src/app/modules/entity/entity.module.ts
- src/app/modules/entity/shared/entity.interface.ts
- src/app/modules/entity/shared/entity.utils.ts
- src/app/modules/entity/shared/store.ts
The data table in igo2-lib is not meant to connect to an AntityStore
The new EntityTable takes a lot of inspiration from the regular data table but it can be used with an EntityStore (and only that).
```
[ ] Yes
[x] No
```
> basic entity table with sorting and selection

- src/app/modules/client/client-schema-form/client-schema-form.component.html
- src/app/modules/client/client-schema-form/client-schema-form.component.ts
- src/app/modules/client/client-schema-form/client-schema-form.module.ts
- src/app/modules/entity/entity-form/entity-form.component.html
- src/app/modules/entity/entity-form/entity-form.component.scss
- src/app/modules/entity/entity-form/entity-form.component.ts
- src/app/modules/entity/entity-form/entity-form.module.ts
- src/app/modules/entity/entity-form/entity-form.variables.scss
- src/app/modules/entity/entity-form/index.ts
- src/app/modules/entity/entity.module.ts
- src/app/modules/entity/index.ts
- src/app/modules/entity/shared/entity.interface.ts
We need to be able to generate on demand entity forms from a config. 
A new entity-form module allows that with, for now, very few options.
```
[ ] Yes
[ ] No
```
> basic entity form module and client schema form

- src/app/modules/client/client-info/client-info.component.html
- src/app/modules/client/client-info/client-info.component.scss
- src/app/modules/client/client-info/client-info.module.ts
- src/app/modules/client/client-legend/client-legend-item.component.scss
- src/app/modules/client/client-legend/client-legend.component.html
- src/app/modules/client/client-schema-form/client-schema-form.component.html
- src/app/modules/client/client-schema-form/client-schema-form.component.ts
- src/app/modules/client/client-schema-selector/client-schema-selector.component.html
- src/app/modules/client/client-schema-selector/client-schema-selector.component.scss
- src/app/modules/client/shared/client-schema-editor.ts
- src/app/modules/common/dynamic-container/dynamic-container.component.ts
- src/app/modules/edition/editor-outlet/editor-outlet.component.html
- src/app/modules/edition/editor-outlet/editor-outlet.component.ts
- src/app/modules/edition/shared/editor.ts
- src/app/modules/entity/entity-form/entity-form.component.html
- src/app/modules/entity/entity-form/entity-form.component.ts
- src/app/modules/map/map-widgetbar/map-widgetbar.component.html
- src/app/modules/map/map-widgetbar/map-widgetbar.component.ts
- src/app/modules/tool/client-info-tool/client-info-tool.component.html
- src/app/modules/tool/client-info-tool/client-info-tool.component.scss
- src/app/modules/tool/client-info-tool/client-info-tool.module.ts
- src/app/modules/widget/shared/widget.interface.ts
- src/app/modules/widget/widgetbar/widgetbar-item.component.ts
- src/app/modules/widget/widgetbar/widgetbar.component.html
- src/app/modules/widget/widgetbar/widgetbar.component.ts
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.component.ts
- src/fadq.theme.scss
- src/locale/en.json
- src/locale/fr.json
There is no way for and enditor to subscribe to a widget events
An editor can subscribe to a widget event. This is still very basic
```
[ ] Yes
[x] No
```
> Editor events

- src/app/modules/client/client-parcel-year-selector/client-parcel-year-selector.component.html
- src/app/modules/client/client-parcel-year-selector/client-parcel-year-selector.component.scss
- src/app/modules/client/client-parcel-year-selector/client-parcel-year-selector.component.ts
- src/app/modules/client/client-parcel-year-selector/client-parcel-year-selector.module.ts
- src/app/modules/client/client.module.ts
- src/app/modules/client/shared/client-parcel-year.service.ts
- src/app/modules/client/shared/client.interface.ts
- src/app/modules/client/shared/client.provider.ts
- src/app/modules/client/shared/index.ts
- src/app/modules/tool/client-info-tool/client-info-tool.component.html
- src/app/modules/tool/client-info-tool/client-info-tool.component.scss
- src/app/modules/tool/client-info-tool/client-info-tool.component.ts
- src/app/state/client.state.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/locale/en.json
- src/locale/fr.json
No parcel year selector
Basic parcel year selector that does nothing.
```
[ ] Yes
[x] No
```
> basic parcel year selector that does nothing for now

- src/app/modules/client/parcel/shared/client-parcel.editor.ts
- src/app/modules/client/parcel/shared/client-parcel.service.ts
- src/app/modules/client/schema/client-schema-create-form/client-schema-create-form.component.html
- src/app/modules/client/schema/client-schema-create-form/client-schema-create-form.component.ts
- src/app/modules/client/schema/client-schema-create-form/client-schema-create-form.module.ts
- src/app/modules/client/schema/client-schema-delete-form/client-schema-delete-form.component.html
- src/app/modules/client/schema/client-schema-delete-form/client-schema-delete-form.component.scss
- src/app/modules/client/schema/client-schema-delete-form/client-schema-delete-form.component.ts
- src/app/modules/client/schema/client-schema-delete-form/client-schema-delete-form.module.ts
- src/app/modules/client/schema/client-schema.module.ts
- src/app/modules/client/schema/shared/client-schema-form-builder.ts
- src/app/modules/client/schema/shared/client-schema.editor.ts
- src/app/modules/client/schema/shared/client-schema.interfaces.ts
- src/app/modules/client/schema/shared/client-schema.service.ts
- src/app/modules/client/schema/shared/index.ts
- src/app/modules/edition/shared/edition.interface.ts
- src/app/modules/edition/shared/editor.ts
- src/app/modules/entity/entity-form/entity-form.component.html
- src/app/modules/entity/entity-form/entity-form.component.ts
- src/app/modules/entity/entity-table/entity-table.component.html
- src/app/modules/entity/entity-table/entity-table.component.ts
- src/app/modules/entity/shared/entity.interface.ts
- src/app/modules/entity/shared/store.ts
- src/app/pages/portal/portal.component.html
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/locale/en.json
- src/locale/fr.json
> first draft at a better form structure

- src/app/modules/client/schema/client-schema-file-manager/client-schema-file-manager.component.html
- src/app/modules/client/schema/client-schema-file-manager/client-schema-file-manager.component.scss
- src/app/modules/client/schema/client-schema-file-manager/client-schema-file-manager.component.ts
- src/app/modules/client/schema/client-schema-file-manager/client-schema-file-manager.module.ts
- src/app/modules/client/schema/client-schema.module.ts
- src/app/modules/client/schema/shared/client-schema-file.service.ts
- src/app/modules/client/schema/shared/client-schema.editor.ts
- src/app/modules/client/schema/shared/client-schema.interfaces.ts
- src/app/modules/client/schema/shared/client-schema.providers.ts
- src/app/modules/client/shared/client.interfaces.ts
- src/app/modules/common/dynamic-container/dynamic-container.component.ts
- src/app/state/client.state.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/locale/en.json
- src/locale/fr.json
No file manager tool
Basic file manager tool with hardcoded data
```
[ ] Yes
[x] No
```
> Schema files

- src/app/modules/map/map.state.ts
- src/lib/client/schema-element/client-schema-element.module.ts
- src/lib/client/schema-element/schema-element-surface-create-form/client-schema-element-surface-create-form.component.html
- src/lib/client/schema-element/schema-element-surface-create-form/client-schema-element-surface-create-form.component.ts
- src/lib/client/schema-element/schema-element-surface-create-form/client-schema-element-surface-create-form.module.ts
- src/lib/client/schema-element/shared/client-schema-element-form.service.ts
- src/lib/client/schema-element/shared/client-schema-element-surface-editor.service.ts
- src/lib/client/schema-element/shared/client-schema-element-surface.utils.ts
- src/lib/client/schema-element/shared/client-schema-element-widget.service.ts
- src/lib/client/schema-element/shared/client-schema-element.interfaces.ts
- src/lib/entity/entity-form/entity-form-field-geometry-input.component.html
- src/lib/entity/entity-form/entity-form-field-geometry-input.component.ts
- src/lib/entity/entity-form/entity-form-field.component.html
- src/lib/entity/entity-form/entity-form.component.ts
- src/lib/entity/entity-form/entity-form.module.ts
- src/lib/entity/entity-table/entity-table.component.ts
- src/lib/entity/shared/entity.interfaces.ts
- src/lib/entity/shared/entity.utils.ts
- src/lib/feature/shared/feature.interfaces.ts
- src/lib/layer/shared/strategies/load.ts
- src/lib/overlay/shared/overlay.ts
- src/locale/en.json
- src/locale/fr.json
No way to draw/modify a geometry and submit it
A new type of input allows that and return accepts/returns GeoJSON
```
[ ] Yes
[x] No
```
> Geometry input

- src/lib/client/schema-element/schema-element-surface-create-form/client-schema-element-surface-create-form.component.ts
- src/lib/client/schema-element/schema-element-surface-update-form/client-schema-element-surface-update-form.component.ts
- src/lib/client/schema/client-schema-create-form/client-schema-create-form.component.ts
- src/lib/client/schema/client-schema-delete-form/client-schema-delete-form.component.ts
- src/lib/client/schema/client-schema-duplicate-form/client-schema-duplicate-form.component.ts
- src/lib/client/schema/client-schema-update-form/client-schema-update-form.component.ts
- src/lib/edition/shared/editor.ts
- src/lib/entity/entity-form/entity-form-field-geometry-input.component.ts
- src/lib/entity/entity-form/entity-form.component.ts
- src/lib/entity/shared/entity.interfaces.ts
- src/lib/feature/feature-form/feature-form.component.ts
- src/lib/feature/shared/feature.interfaces.ts
- src/lib/map/shared/controls/draw.ts
- src/lib/map/shared/controls/index.ts
- src/lib/map/shared/controls/modify.ts
- src/lib/measure/measurer/measurer.component.ts
- src/lib/measure/shared/measure.utils.ts
No modify control. Eveything is done in the entity-form-geometry-input
Modify control and some improvements here and there following that
```
[ ] Yes
[x] No
```
> Modify control

- src/lib/client/schema-element/schema-element-surface-create-form/client-schema-element-surface-create-form.component.ts
- src/lib/map/shared/controls/draw.ts
- src/lib/map/shared/controls/modify.ts
- src/lib/measure/measurer/measurer.component.ts
- src/lib/measure/shared/measure.interfaces.ts
- src/lib/measure/shared/measure.utils.ts
- src/styles.scss
No measure tooltips on the map
Measure tooltips at every midpoints of the geoemtry being drawn
```
[ ] Yes
[x] No
```
> Measure tooltips

- src/lib/client/schema-element/client-schema-element.module.ts
- src/lib/client/schema-element/schema-element-surface-split-form/client-schema-element-surface-split-form.component.html
- src/lib/client/schema-element/schema-element-surface-split-form/client-schema-element-surface-split-form.component.ts
- src/lib/client/schema-element/schema-element-surface-split-form/client-schema-element-surface-split-form.module.ts
- src/lib/client/schema-element/shared/client-schema-element-form.service.ts
- src/lib/client/schema-element/shared/client-schema-element-surface-editor.service.ts
- src/lib/client/schema-element/shared/client-schema-element.widgets.ts
- src/lib/feature/shared/feature.utils.ts
- src/lib/measure/measurer/measure-format.pipe.ts
- src/lib/measure/measurer/measurer-item.component.html
- src/lib/measure/measurer/measurer-item.component.ts
- src/lib/measure/measurer/measurer.component.html
- src/lib/measure/measurer/measurer.component.scss
- src/lib/measure/measurer/measurer.component.ts
- src/lib/measure/shared/measure.enum.ts
- src/lib/measure/shared/measure.interfaces.ts
- src/lib/measure/shared/measure.utils.ts
- src/locale/en.json
- src/locale/fr.json
- src/styles.scss
No auto measure mode
Auto measure mode
```
[ ] Yes
[x] No
```
> Auto measure

- src/app/pages/portal/portal.component.ts
- src/lib/measure/measurer/measurer.component.ts
- src/lib/query/queryable/queryable.directive.ts
- src/lib/search/search-results/search-results.component.ts
The prod build fails because of the query directive.
The prod build is now fixed and the query directive still works as expected.
```
[ ] Yes
[x] No
```
> fix(build): build error caused by the query directive

- src/app/modules/client/client.state.ts
- src/app/pages/portal/portal.component.scss
- src/lib/map/map-actionbar/map-actionbar.component.ts
- src/lib/map/shared/map.enum.ts
The previous and next view buttons do nothing.
The previous and next view buttons do what's expected.
```
[ ] Yes
[x] No
```
> Map previous next view

- package.json
- src/fadq.theme.scss
- src/lib/client/schema-element/schema-element-create-form/client-schema-element-create-form.component.html
- src/lib/client/schema-element/schema-element-create-form/client-schema-element-create-form.component.ts
- src/lib/client/schema-element/schema-element-create-form/client-schema-element-create-form.module.ts
- src/lib/client/schema-element/schema-element-saver/client-schema-element-saver.component.ts
- src/lib/client/schema-element/schema-element-slice-form/client-schema-element-slice-form.component.html
- src/lib/client/schema-element/schema-element-slice-form/client-schema-element-slice-form.component.scss
- src/lib/client/schema-element/schema-element-slice-form/client-schema-element-slice-form.component.ts
- src/lib/client/schema-element/schema-element-slice-form/client-schema-element-slice-form.module.ts
- src/lib/client/schema-element/schema-element-update-form/client-schema-element-update-form.component.html
- src/lib/client/schema-element/schema-element-update-form/client-schema-element-update-form.component.ts
- src/lib/client/schema-file/client-schema-file-manager/client-schema-file-manager.component.ts
- src/lib/client/schema/client-schema-create-form/client-schema-create-form.component.ts
- src/lib/client/schema/client-schema-delete-form/client-schema-delete-form.component.ts
- src/lib/client/schema/client-schema-duplicate-form/client-schema-duplicate-form.component.ts
- src/lib/client/schema/client-schema-update-form/client-schema-update-form.component.ts
- src/locale/en.json
- src/locale/fr.json
The schema element slicer doesn't do anything
The schema element slicer works as expected
```
[ ] Yes
[x] No
```
> feat(slice): client schema element slicer

- src/app/modules/client/client-schema-confirm-dialog/client-schema-confirm-dialog.component.html
- src/app/modules/client/client-schema-confirm-dialog/client-schema-confirm-dialog.component.scss
- src/app/modules/client/client-schema-confirm-dialog/client-schema-confirm-dialog.component.ts
- src/app/modules/client/client-schema-confirm-dialog/client-schema-confirm-dialog.module.ts
- src/app/modules/client/client-schema-confirm-dialog/index.ts
- src/app/modules/client/client-schema-element.state.ts
- src/app/modules/client/client.module.ts
- src/app/modules/client/client.state.ts
- src/app/pages/portal/portal.component.ts
- src/lib/client/schema-element/client-schema-element-saver/client-schema-element-saver.component.ts
- src/lib/client/schema-element/shared/client-schema-element.service.ts
- src/lib/client/schema/client-schema-selector/client-schema-selector.component.html
- src/lib/client/schema/client-schema-transfer-form/client-schema-transfer-form.component.ts
- src/lib/client/schema/shared/client-schema.interfaces.ts
- src/lib/client/schema/shared/client-schema.service.ts
- src/locale/en.json
- src/locale/fr.json
No confirmation dialog when a new client or schema is selected and the current transaction contains unsaved changes.
Confirmation dialog when a new client or schema is selected and the current transaction contains unsaved changes.
```
[ ] Yes
[x] No
```
> Schema dialog

- src/app/modules/client/client-schema-element.state.ts
- src/environments/environment.partial.ts
- src/environments/environment.ts
- src/lib/client/schema-element/client-schema-element-saver/client-schema-element-saver.component.html
- src/lib/client/schema-element/client-schema-element-saver/client-schema-element-saver.component.scss
- src/lib/client/schema-element/client-schema-element-saver/client-schema-element-saver.component.ts
- src/lib/client/schema-element/shared/client-schema-element-form.service.ts
- src/lib/client/schema-element/shared/client-schema-element-line.service.ts
- src/lib/client/schema-element/shared/client-schema-element-point.service.ts
- src/lib/client/schema-element/shared/client-schema-element-surface.service.ts
- src/lib/client/schema-element/shared/client-schema-element.interfaces.ts
- src/lib/client/schema-element/shared/client-schema-element.service.ts
- src/lib/client/schema-element/shared/client-schema-element.utils.ts
- src/locale/en.json
- src/locale/fr.json
Schema elements cannot be saved
Schema elements can be saved
```
[ ] Yes
[x] No
```
> feat(elements): save schema elements

- src/app/modules/cadastre/cadastre-search-tool/cadastre-search-tool.component.ts
There's a bug withe the states of layers.
The layers are now completely in the states.
```
[ ] Yes
[ x] No
```
> Correct a bug with the states of layers

- src/app/pages/portal/portal.component.ts
There's no related search layers on a search result type.
There's related layers who are activated or not depending the search result type.
```
[ ] Yes
[ x] No
```
> Commit before a code review.

- src/lib/address/address-editor-save-dialog/address-editor-save-dialog.component.ts
- src/lib/address/address-editor/address-editor.component.html
- src/lib/address/address-editor/address-editor.component.ts
- src/lib/client/schema-element/shared/client-schema-element-form.service.ts
- src/locale/en.json
- src/locale/fr.json
The edition mode is not closed after a save.
The edition mode is closed after a save.
```
[ ] Yes
[ x ] No
```
> After the save, must close the edition mode

- src/app/app.module.ts
- src/app/modules/cadastre/cadastre-search-tool/cadastre-search-tool.component.ts
- src/app/modules/client/client-tool/client-tool-item.component.html
- src/app/modules/client/client-tool/client-tool.component.ts
- src/app/modules/help/help-tool/help-tool.component.html
- src/app/modules/help/help-tool/help-tool.component.ts
- src/app/modules/map/map-tool/map-tool.component.html
- src/app/modules/navigation/navigation-tool/navigation-tool.component.ts
- src/app/pages/portal/expansion-panel/expansion-panel-header.component.html
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/sidenav/sidenav.component.html
- src/app/pages/portal/toast-panel/toast-panel.component.html
- src/contexts/_default.json
- src/contexts/agroclim.json
- src/lib/cadastre/concession/concession-selector/cadastre-concession-selector.component.html
- src/lib/cadastre/concession/concession-selector/cadastre-concession-selector.component.scss
- src/lib/cadastre/lot/lot-selector/cadastre-lot-selector.component.html
- src/lib/cadastre/lot/lot-selector/cadastre-lot-selector.component.scss
- src/lib/client/parcel-element/shared/client-parcel-element-actions.service.ts
- src/lib/client/parcel/shared/client-parcel-actions.service.ts
- src/lib/client/schema-element/shared/client-schema-element-actions.service.ts
- src/lib/client/schema-file/client-schema-file-manager/client-schema-file-manager.component.html
- src/lib/client/schema/shared/client-schema-actions.service.ts
- src/lib/edition/edition-save/edition-save.component.ts
- src/lib/map/map-actionbar/map-actionbar.component.ts
> chore(material font): upgrade to material design font

- src/apps/interne/modules/client/shared/client-parcel-table.service.ts
- src/lib/client/parcel/shared/client-parcel.interfaces.ts
- src/locale/en.json
- src/locale/fr.json
Must use a new property from the service to get parcels and few minor changes on some labels.
The new property is used and the labels are changed.
```
[ ] Yes
[ X ] No
```
> Statut iasc

- src/apps/interne/modules/client/shared/client-parcel-element-actions.service.ts
- src/environments/interne/environment.partial.ts
- src/lib/client/parcel-element/client-parcel-element-without-owner/client-parcel-element-without-owner.component.ts
- src/lib/client/parcel-element/shared/client-parcel-element.interfaces.ts
- src/lib/client/parcel-element/shared/client-parcel-element.service.ts
- src/lib/client/parcel-element/shared/client-parcel-element.utils.ts
- src/locale/en.json
- src/locale/fr.json
The service to get parcels without owner return only parcels who has never been owned.
The service has been changed to return parcels from others years who do not touch parcels from current edit year. 
```
[ ] Yes
[ X ] No
```
> Parcels without owner

- angular.json
- src/lib/client/info/shared/client-info.service.ts
info-client-adress use a null property from the service.
info-client-adress use a property with a valid adress.
```
[ ] Yes
[ x ] No
```
> property change to fit a service change

- src/apps/interne/modules/client/shared/client-parcel-element-table.service.ts
- src/apps/interne/modules/client/shared/client-parcel-table.service.ts
- src/apps/pes/modules/client/shared/client-parcel-table.service.ts
- src/apps/shared/modules/context/context.module.ts
- src/apps/shared/modules/help/help-tool/help-tool.component.ts
- src/apps/shared/modules/map/map-tool/map-tool.component.html
- src/apps/shared/modules/map/map-tool/map-tool.component.scss
- src/apps/shared/modules/map/map-tool/map-tool.component.ts
- src/apps/shared/modules/map/map-tool/map-tool.module.ts
- src/environments/interne/environment.partial.ts
- src/environments/pes/environment.partial.ts
- src/environments/pes_interne/environment.partial.ts
- src/lib/client/parcel-element/client-parcel-element-transfer/client-parcel-element-transfer.component.ts
- src/lib/context/context.module.ts
- src/lib/context/index.ts
- src/lib/context/shared/context.interfaces.ts
- src/lib/context/shared/context.providers.ts
- src/lib/context/shared/context.service.ts
- src/lib/context/shared/index.ts
- src/lib/core/core.module.ts
- src/locale/en.json
- src/locale/fr.json
There's no save context.
Units of measure Acre and Arpent are not shown on parcels table.
During a complete transfer, parcels numbers are not kept.
There's a save context tool.
Units of measure Acre and Arpent are shown on parcels table.
During a complete transfer, it's possible to keep parcels numbers.
```
[ ] Yes
[ X] No
```
> Save context

- src/apps/interne/modules/client/shared/client-schema-element-workspace.service.ts
- src/lib/client/schema-element/shared/client-schema-element.service.ts
- src/lib/client/schema-element/shared/client-schema-element.utils.ts
- src/lib/client/schema/shared/client-schema-form.service.ts
- src/lib/client/schema/shared/client-schema-validators.ts
- src/lib/client/schema/shared/client-schema.enums.ts
- src/lib/client/schema/shared/client-schema.service.ts
- src/lib/client/schema/shared/client-schema.utils.ts
- src/lib/core/domain/domain.service.ts
Some schema types are not present.
A few types of diagrams are now accessible
```
[ ] Yes
[ X ] No
```
> New schema types

- .gitignore
- src/apps/interne/app.module.ts
- src/apps/interne/modules/client/shared/client-parcel-element-table.service.ts
- src/apps/interne/modules/client/shared/client-parcel-table.service.ts
- src/apps/interne/modules/client/shared/client-schema-element-table.service.ts
- src/apps/interne/modules/client/shared/client-schema-table.service.ts
- src/apps/interne/views/portal/portal.component.html
- src/apps/interne/views/portal/portal.component.ts
- src/apps/pes/modules/client/shared/client-parcel-table.service.ts
- src/apps/pes/views/portal/portal.component.ts
- src/apps/shared/app-outlet/app-outlet.component.scss
- src/apps/shared/modules/map/map-tool/map-tool.component.html
- src/apps/shared/modules/map/map-tool/map-tool.component.scss
- src/contexts/templates/interne.default.json
- src/contexts/templates/interne.json
- src/contexts/templates/pes.json
- src/lib/client/info/shared/client-info.service.ts
- src/lib/context/shared/context.service.ts
- src/lib/core/core.module.ts
- src/lib/map/shared/map.utils.ts
- src/styles.scss
The advanced map tools doesn't work.
The advanced map tools work.
```
[ ] Yes
[ X ] No
```
> Advanced map tools

- package.json
- src/apps/interne/modules/client/shared/client-schema-element-actions.service.ts
- src/apps/pes/app.module.ts
- src/apps/pes/views/portal/portal.component.html
- src/apps/pes/views/portal/portal.component.ts
- src/apps/pes_interne/app.module.ts
- src/lib/client/schema-element/shared/client-schema-element-form.service.ts
- src/lib/edition/edition-import/edition-import.component.ts
- src/lib/edition/edition-upsert/edition-upsert.component.ts
The element type field can't be modified in batch.
The coordinates of all geometries created or modified are not truncated.
The element type field can be modified in batch.
The coordinates of all geometries created or modified are truncated.
```
[ ] Yes
[ X ] No
```
> Schema element update batch type

- src/lib/cadastre-reno/shared/cadastre-reno.interfaces.ts
- src/lib/cadastre-reno/shared/cadastre-reno.ts
- src/lib/client/schema-element/client-schema-element-create/client-schema-element-create.component.ts
- src/lib/client/schema-element/client-schema-element-slice/client-schema-element-slice.component.ts
- src/lib/client/schema-element/client-schema-element-translate/client-schema-element-translate.component.ts
- src/lib/client/schema-element/client-schema-element-update/client-schema-element-update.component.ts
- src/lib/client/schema-element/shared/client-schema-element-form.service.ts
- src/lib/client/schema-element/shared/client-schema-element.service.ts
- src/lib/client/schema-element/shared/client-schema-element.utils.ts
The image year is calculated by the extent of map on the opening of the create-schema-form.
The image year is calculated with the geometry of the schema element when it is created and modified.
```
[ ] Yes
[ X ] No
```
> Schem element image year
